debug: false

database:
  use: LOCAL # LOCAL,MYSQL(没写)
  sql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: bukkit_plugin

#示范
#limit-condition{value=1;message=&4| &8系统 &7-> &e%player_name% &c的进入次数不足} @system

limit:
  fire: 10
  water: 10
  anying: 5
  guangming: 5
  boss1: 10
  fuxi: 3
  Ozruk: 1
  Jokull: 1
  Bhunivelze: 1
  KelThuzad: 1
  Amalgam: 1
  Cenarius: 1
  Exodus: 1
  Atlas: 1

count: 1
name: "%player_name% 的亡魂"