debug: false


#%CupDungeonManager_count%          复活币
#%CupDungeonManager_limit_dungeon%  副本限制次数
#%CupDungeonManager_alive%          是否死亡
database:
  use: LOCAL # LOCAL,MYSQL(没写)
  sql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: bukkit_plugin

#示范
#limit-condition{value=1;message=&4| &8系统 &7-> &e%player_name% &c的进入次数不足} @system

limit:
  test1: 3
  test2: 3

#每日刷新复活币数量
count: 1
#坟墓的名字
name: "%player_name% 的亡魂"

#地牢内玩家可以使用的免费复活次数 (未设置的副本则视为0):
DungeonsReviveFreeTimes:
  test1: 3
  test2: 3

#地牢内每个玩家可以使用复活币的最大次数 (未设置的副本则视为无限制):
DungeonsReviveLimit:
  test1: 3
  test2: 3
